title: Mayank Kashyap's Blog
description: Blog of Mayank Kashyap

url: http://mayankkashyap.com
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Blog
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: kspmayank
   twitter: kspmayank
   facebook: kspmayank
   email: contact@mayankkashyap.com

#google_analytics: "UA-58263416-1"
