title: Mayank Kashyap's Blog
description: Blog of Mayank Kashyap

url: http://mayankkashyap.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: kspmayank
   twitter: kspmayank
   facebook: kspmayank
   email: contact@mayankkashyap.com

google_analytics: "UA-58263416-1"
